services:
  - type: web
    name: civicsync-backend
    env: node
    buildCommand: npm install --prefix backend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
